### ISSUE TITLE
So sorry for asking question here..but if you have free time give me some advice.

### ISSUE THREAD

**Issue by ytianzaishui** [Dayanara847/tubesoft-test-dayanara-maurin#1]
I have a question that I can't use the database container _name from `docker-compose.y` to  connect database ...But I see you did it in your code 
```js
// Create a Sequelize instance to connect to the DB.
let sequelize = new Sequelize(config.database, config.username, config.password, config);
```
I post a little demo .[ link here](https://github.com/Chen-WeiZhen/docker-deploy). if you have free time give me some help.
thank you in advance.

**Comment by Dayanara847** [comment]
Hello ytianzaishui,
Sorry for taking so long to reply.

I'm new to Docker, I just learned it recently and don't have much experience. However, I will try to help you with what I can.

I was looking at your code, I tried running it on my PC to see if I could find the error.
The first thing that caught my attention is the value you were passing in _host_ in the Sequelize connection, I understand that in line 33 of the docker-compose.yml you are telling it that the HOST of the DB will be 'db'. I changed that.

The second thing I changed is the database name, I left it as db, as well as the name you gave the database service in the docker-compose.yml. I don't know why it doesn't want to take the name 'fendou', maybe it has to do with the MYSQL variables (which I doubt are being used, since the user doesn't correspond to the one you use for the Sequelize connection).

With those two changes everything seems to be working properly:

![imagen](https://user-images.githubusercontent.com/66930743/117080162-4ba0b180-ad0b-11eb-9a96-a701381a73e4.png)

Sorry I can't help you more, that's as far as my experience goes 😂.

I hope it will help you.
Regards!

Translated with www.DeepL.com/Translator (free version)

**Comment by Dayanara847** [comment]
Hello ytianzaishui,
Sorry for taking so long to reply.

I'm new to Docker, I just learned it recently and don't have much experience. However, I will try to help you with what I can.

I was looking at your code, I tried running it on my PC to see if I could find the error.
The first thing that caught my attention is the value you were passing in _host_ in the Sequelize connection, I understand that in line 33 of the docker-compose.yml you are telling it that the HOST of the DB will be 'db'. I changed that.

The second thing I changed is the database name, I left it as db, as well as the name you gave the database service in the docker-compose.yml. I don't know why it doesn't want to take the name 'fendou', maybe it has to do with the MYSQL variables (which I doubt are being used, since the user doesn't correspond to the one you use for the Sequelize connection).

With those two changes everything seems to be working properly:

![imagen](https://user-images.githubusercontent.com/66930743/117080284-80146d80-ad0b-11eb-98dd-00dd8c65d504.png)

Sorry I can't help you more, that's as far as my experience goes 😂.

I hope it will help you.
Regards!

**Comment by ytianzaishui** [comment]
Thank you for your reply, It's so kind of you!
From your code,I get the problem bellow
```js
const sequelize = new Sequelize(DB_DATABASE, DB_USERNAME, DB_PASSWORD, {
  //port: DB_PORT, ----> error come from here. so shame!
  host: process.env.DB_HOST || DB_HOST
}
```
anyother is no problem.
Thanks again !

**Comment by Dayanara847** [comment]
Can I see the problem? Do you have a screenshot?
With my database manager I can see the base on the correct port (33061) without passing it to the Sequelize configuration object.

![imagen](https://user-images.githubusercontent.com/66930743/117204236-08534b00-adbe-11eb-8471-de6f645aa4d9.png)
